### ISSUE TITLE
Support R Markdown Site. Entrypoint being identified as a single R Markdown Doc.

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#1643]
Example: https://github.com/rstudio/connect-content/tree/main/bundles/rmd-site

This example is getting initialized as an `rmd` and Connect is treating it as an `R Markdown Document`.  It should be an `rmd-site` so Connect will treat it as an `R Markdown Site`.

Since it's an `R Markdown Document` the links are broken in Connect.

Here's the example deployed with publisher client:
https://rsc.radixu.com/connect/#/apps/7562e43e-af3d-4d67-9d72-4a34df032684/access/6545

And the same example published with the IDE:
https://rsc.radixu.com/connect/#/apps/e7c076ae-12ce-4027-b03e-db50446b2ae7/info/6547

**Comment by kgartland-rstudio** [comment]
Update...

When we use the `render with Quarto` option in the dropdown this works as expected and gets a `Quarto Document` type in Connect.

When using `render with rmarkdown/knitr` option, this continue to fails and gets an `R Markdown document` type in Connect.

**Comment by dotNomad** [comment]
Moving into `1.6.0 to retest, and we can determine if we want to keep it in the `1.6.0` milestone based on what we learn.

**Comment by marcosnav** [comment]
This is still happening. While investigating it turns out we don't have support for `rmd-site` content type at all.

Breaking down the requirements, that I noticed, to make this work:
- The `RMarkdownDetector` has to look for a `_site.yml`
- If `_site.yml` is present, then the content type should be treated as `rmd-site`
- `.Rmd` files can have links to unrendered `.html` files. In order to not have broken links, and to help the user to have related files included in the deployment, we have to look for and include `.Rmd` files from the provided base directory while traversing up to children directories.

**Comment by marcosnav** [comment]
Updated the Issue title to reflect the actual problem.

**Comment by marcosnav** [comment]
Seeing this issue with a new perspective, it is a files discoverability issue.

To be clear:
**We do support RMarkdown sites**

This is a user experience problem, RMD files that generate static resources are not included when inspecting the project and that's why some links within the deployed document do not work.

The question is, does the work required to inspect and find all related resources is worth doing?

IMO, the user will know much more about the project and can add files manually, something that we might not be able to fulfill entirely.

Using the [geocompx/geocompr bookdown project](https://github.com/geocompx/geocompr) as an example, `.Rmd` files on this project require resources of many types, not just other `.Rmd` pages, but also `.R` files with code, images, CSS files, data on `.csv` files, etc. And, for most of these, the user can just check some directories on the file inspector to have required assets included in the deployment.

**Comment by marcosnav** [comment]
While investigating how the RStudio IDE handles Rmd websites discovered that when there is a `_site.yml` file, it includes every single  asset located on the working directory, regardless of the usage, with some exceptions e.g: leaving out `renv` directory, `.Rhistory`...

So, the first step on helping users here will be to replicate that, I'll work towards selecting all existing files and directories at the same level of the chosen entrypoint when there is a `_site.yml` or a `_bookdown.yml` file present.

**Comment by jonkeane** [comment]
> While investigating how the RStudio IDE handles Rmd websites discovered that when there is a _site.yml file, it includes every single asset located on the working directory, regardless of the usage

Hmmm, I'm actually a little surprised by that. It probably makes sense for many sites to do this (and it certainly increases the chances that the site will be renderable if you send up everything!). And looking at the source of rsconnect:  https://github.com/rstudio/rsconnect/blob/a7c93ba015dca20a1c1fba393475b0b1538d1573/R/deploySite.R#L58-L63 (and also https://github.com/rstudio/rsconnect/blob/a7c93ba015dca20a1c1fba393475b0b1538d1573/R/deployApp.R#L29-L34) are where the directory is added (and by default, if no files are listed they are all included with some exceptions). So that works / is documented for rsconnect. 

If we do this (and I think it probably makes sense as the past of least surprise), we should make sure that quarto and rmarkdown sites behave similarly with respect to file inclusions and to clearly document that sites include the whole directory when most other types do not.

**Comment by aronatkins** [comment]
RStudio is also involved during push-button deploy. I'm not 100% sure this is the active code path, but in at least some cases, it calls `rsconnect::listBundleFiles()`. There may be other paths used to compute the set of files shown in the file picker. https://github.com/rstudio/rstudio/blob/38a7a858c6257fafedc509da325b4d37bbbfd674/src/cpp/session/modules/SessionRSConnect.R#L454

**Comment by dotNomad** [comment]
Verified the behavior as part of the PR review process
