### ISSUE TITLE
Use selected R interpreter in Positron

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#1968]
Use the `acquirePositronApi()` function to get the API, then call `getPreferredRuntime('r')`.

Example [here](https://github.com/quarto-dev/quarto/blob/06678d55143a7d6de6c7f0232db0c5dcf8392ca6/apps/vscode/src/host/hooks.ts#L24-L43)

https://positpbc.slack.com/archives/C02P4PH94QL/p1720038787421989?thread_ts=1720037285.378959&cid=C02P4PH94QL

**Comment by sagerb** [comment]
Notes from the 11/20/24 product team discussion, after demoing the proposed fix in which a mismatch of the R version was possible between the values within the configuration vs. the `renv.lock` file. (See PR notes: https://github.com/posit-dev/publisher/pull/2126#issuecomment-2486807520)

The root of awkwardness with the user experience is due to the current implementation that records the version of R in use within both the Config file as well as the renv.lock file. The new proposal is to eliminate it from the config file and use the renv.lock file as source of truth.

This will entail:
- Creating a new config schema version in which we remove it
- Conversion of old configuration files into new schema by dropping the value. 
    - NOTE: what should we do about the scenario in which the config file had a different version (which would have been used on Connect), but now we’re removing it to then use whatever version is in renv.lock?)(Jordan) I’d be in favor of just removing it, and relying entirely on renv.lock 
- Not implementing POC messaging shown by Bill today
- Eliminating inspection’s need to execute R - which we think is basically there now and only needed the version of R to place into the initial configuration.
- Confirm the pre-check functionality that if we do not have a renv.lock file with a version, that we fail the deployment.
- Update the code creating the manifest to pull the r version from renv.lock file rather than the config.

Bill will get going on these changes immediately and will pull his existing PR.

**Comment by jonkeane** [comment]
> Eliminating inspection’s need to execute R - which we think is basically there now and only needed the version of R to place into the initial configuration.

I'm not sure we want to eliminate this entirely. If it's there and we can leave it intact, let's not do extra work to pull it out just yet. I suspect where we're going to go next with our fit and finish improvements of R dependency management will be to have the publisher call `renv::status()` and if things aren't clean recommend someone go to that and figure out what's going on. In which case we will need _some_ functionality to call R.

**Comment by dotNomad** [comment]
Verified the behavior as outlined in your comment @sagerb: https://github.com/posit-dev/publisher/pull/2126#issuecomment-2486807520

When a `renv.lock` exists a generated config uses that `r.version`, but when `renv.lock` doesn't exist then the config sets `r.version` to the selected interpreter.
