### ISSUE TITLE
Fully remove configurations and deployments in the left side bar

### ISSUE THREAD

**Issue by jonkeane** [posit-dev/publisher#1996]
We've talked about this a bit already, and hidden them, but watching the user interview session today they are massively confusing even for someone who is an expert about connect + publishing.

**Comment by dotNomad** [comment]
Some functionality is in these views that could be transferred as part of this task, or another follow-up. Some of them have to removed in my opinion with only the "Home" view.
- Rename/delete deployments (can be done in the file system)
  - We lose the forget language, and the custom confirmation, but that is alright. We could move these to the "more" menu in the Deployment selector
- "View Deployment" to see the deployed content
  - We already have "View Content", but it requires users select through each Deployment rather than seeing a full list and clicking through each quickly. I don't think this has a good replacement, so could just be removed
- Rename/delete configurations (can be done in the file system)
  - Not having it in our view though does mean we cannot do #1588. We could move this to the "more" menu in the Deployment selector as well
- Clone configurations
  - This one doesn't make a lot of UX sense in the "more" menu for the Deployment selector since it will create a Configuration behind the scenes that cannot be seen and is not used anywhere. It will only be visible in the file system. I think because of this poor UX we would need to remove the clone functionality.
