### ISSUE TITLE
Design import past deployments from Connect Server feature

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#2019]
We will need to break this down, and create a design document for exactly how we want to do importing.

Will this be just for the IDE, what about rsconnect, or importing from the server?

**Comment by jonkeane** [comment]
> Will this be just for the IDE, what about rsconnect, or importing from the server?

regardless of if we go down the path of also importing from deployments made from rsconnect, we should break this down and ship it incrementally (we must not tie ourselves to it being complete for all of these things before we ship the first thing). And especially breaking it down incrementally where it addresses a whole problem that a user might have

I'm happy to contribute this to a doc somewhere, but IMHO the order of priority should be:

* import from connect URL/guid into publisher or positron (this gets us a plausible story for "I published this thing from rstudio, but I now want to use positron with it")
* something in connect that can trigger ^^^ via something like `vscode://..` or `positron://..` (this enhances / reinforces that above story, and is part of connect is production + plays well with others).
* wire ^^^ up into workbench / the switches we need to detect if someone has workbench to offer that as an option (this reenforces + demonstrates that Posit's products work well together)
* other things (like importing old dcf files from `rsconnect`, or importing old metadata files from `rsconnect-python`) (this is sweeping up the rest of the space around importing. But this alone is less valuable than doing ^^^ since those tell a compelling story as features on their own, this is just about transferring metadata locally, and maybe once we get here we reevaluate how important + helpful + how much leverage this gives us compared to something else.)

**Comment by dotNomad** [comment]
We need to pull down some information when we import (like the Title), but we don't need to fill out the entire configuration at the start of this feature.

The version of R and Python would be helpful as well to avoid issues with version mismatch on the local machine.

**Comment by sagerb** [comment]
Document under review:
https://docs.google.com/document/d/1hbItn4bOs6eYbM_2uzR4-83TtXkTZ-Oqtbie2huPXeo/edit?usp=sharing

**Comment by sagerb** [comment]
Closing, as we have moved to a simpler initial implementation: #2285
