### ISSUE TITLE
Prompt User to confirm scanning directories if number of directories is over some threshold

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2237]
I was testing the permissions failures yesterday and to do so, I opened my Home directory and then tried to Select an entrypoint.  

The scan (understandably) took nearly two full minutes.  I'm wondering if we should prompt the user if they'd really like us to scan their entire directory structure in cases like these.  Maybe we could do a quick count of directories and it's over x, we prompt the user to confirm.

I did see we got a report from a user doing exactly this, opening a home directory and wanting to scan from there.

>  I also noticed that I need to open a specific folder before trying to create the deployment or it will try and scan my entire home directory.

https://positpbc.slack.com/archives/C05D7NZD52S/p1724761830685139

I wonder if users might think they're going to get to select which directory to scan when clicking `Select...`, rather than scanning every file for an entrypoint without warning.

**Comment by dotNomad** [comment]
A few extensions in VS Code have window notifications that pop up if scans of the workspace are taking a long time (like Pylance). We could implement something like that.

VS Code rarely has confirms and doesn't really have a good flow for that. We could do something in the webview for this, but it will probably feel a bit strange.

We have also discussed possibly paginating the scan when we go over a certain quantity of possible entrypoints.

**Comment by sagerb** [comment]
Agreed, it is extremely common for VSCode extensions to not handle scanning large directories very well. 

If we would approach the idea of limiting the scans, it would probably make the most sense to users to have it limited to X levels deep, rather than just a limit on files examined within our walking algorithm, which probably travels leaf-first. We'd also have to identify a way to inform the user that we had stopped and offer them a way to restart without the limit.

Another option might be to put up a status message that has a cancel button when we detect our scan API has gone too long. We may not be able to cancel the scan, but we can at least reset the UX or offer the user the recommendation that they open a smaller workspace.

There is not a great answer here and I agree with Jordan, there is very little prior art for existing extension behavior when workspaces are huge.

**Comment by mmarchetti** [comment]
> Another option might be to put up a status message that has a cancel button when we detect our scan API has gone too long. We may not be able to cancel the scan, but we can at least reset the UX or offer the user the recommendation that they open a smaller workspace.

This is what we discussed at our sync meeting.

**Comment by jonkeane** [comment]
Hmm, I might have missed this while I was out, but I thought that we had implemented (or maybe just _were going to_ implement) doing limited entrypoint detection based on files that are open and then giving someone an out that lets them scan deeper / select entrypoints that aren't open? This would (generally) mean the number of entrypoints to be scanned is relatively low, and most likely to be the files that someone has top of mind (since they are open)

**Comment by sagerb** [comment]
Group action:
- Will address this by changing the entrypoint selection to simply show open files as well as a file picker which will launch VSCode's file dialog.
- Related to

**Comment by dotNomad** [comment]
Verified that the new multi-stepper for creating a Deployment shows the open files, and a generic "Open..." file picker dialog.
