### ISSUE TITLE
Remove `isEntrypoint` in the files API

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#2243]
Currently the `isEntrypoint` attribute is incorrect (it is always `false`) and we have other easy ways to determine if a file is the entrypoint.

This task is to remove it.

**Comment by jonkeane** [comment]
Is there more context about what this is / what is important about it?

**Comment by mmarchetti** [comment]
Yes, this was added as an enabler for #2239. However, we discussed in sync that the extension could compare the current configuration's entrypoint to the file relative path to determine if it's the entrypoint.

**Comment by jonkeane** [comment]
Aaaah got it, thanks!

**Comment by dotNomad** [comment]
Since #2239 can be completed without this attribute it may be best to remove it entirely.

There is a fair bit of complexity to make this attribute return when using `/api/configurations/$NAME/files` and not when using `/api/files` plus passing the configuration optionally.

I think we should remove the attribute to avoid confusion and open an issue if we determine it is necessary in the future.

**Comment by jonkeane** [comment]
> I think we should remove the attribute to avoid confusion and open an issue if we determine it is necessary in the future.

:100: Yeah, if we're not going to use it (and it's wrong) 🚮

**Comment by dotNomad** [comment]
> > I think we should remove the attribute to avoid confusion and open an issue if we determine it is necessary in the future.
> 
> 💯 Yeah, if we're not going to use it (and it's wrong) 🚮

I'll update the issue to remove it 🔥
